# Generated by Django 5.1.15 on 2026-09-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(db_index=True, max_length=64)),
                ('phone', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('text', models.CharField(max_length=255)),
                ('applies_when', models.JSONField(default=list, help_text='List of symptom keys')),
                ('options', models.JSONField(default=list, help_text='List of dicts: [{id, label, keywords: list[str], effects: {cause_key: delta}}]')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('price_min', models.IntegerField(help_text='Minimum price in INR')),
                ('price_max', models.IntegerField(help_text='Maximum price in INR')),
                ('duration_hours', models.FloatField(help_text='Estimated service duration in hours')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=64)),
                ('keywords', models.JSONField(default=list, help_text='List of keywords/phrases')),
                ('red_flag', models.BooleanField(default=False)),
                ('safety_msg', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes', to='kb.servicecatalog')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='CauseSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Weight from 0.0 to 1.0')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_links', to='kb.cause')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_links', to='kb.symptom')),
            ],
            options={
                'ordering': ['cause', '-weight'],
                'unique_together': {('cause', 'symptom')},
            },
        ),
    ]
