# Generated by Django 5.1.15 on 2026-09-25 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField()),
                ('severity', models.PositiveSmallIntegerField(default=2)),
                ('ranked', models.JSONField(default=list)),
                ('evidence_hash', models.CharField(db_index=True, max_length=64)),
                ('safety_alert', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='chat.conversation')),
                ('top_cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='kb.cause')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
