# Generated by Django 5.1.15 on 2026-09-25 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('diagnosis', '0001_initial'),
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(db_index=True, max_length=64)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='chat.conversation')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='diagnosis.diagnosis')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='kb.mechanic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='kb.servicecatalog')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('mechanic', 'scheduled_at'), name='unique_mechanic_confirmed_slot')],
            },
        ),
    ]
