# Generated by Django 5.1.15 on 2026-09-25 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICache',
            fields=[
                ('key', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=32)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('media_image', 'Media Image'), ('media_audio', 'Media Audio'), ('media_video', 'Media Video'), ('extract_text', 'Extract Text')], max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=True)),
                ('conversation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
